### ISSUE TITLE
Tasks from each week given by the professor

### ISSUE THREAD

**Issue by OpariucRares** [Ducks-Net/SiDiez#89]
# Tasks every week

First week
- [x] upgrade de la .NET 6 la .NET 7 (+ un mic raport din care sa reiasa: provocari, daca a fost necesar refactoringul si de asemenea sa studiati cu ce vine nou versiunea 7)
- [x] toate proiectele sa aiba teste de integrare
- [x] toate proiectele sa aiba 2/3 screen-uri (frontend) care sa consume API-urile de pe backend(deci functionalitate end to end cum se zice sau E2E)

Second week
- [x] 100% code coverage pentru domain
- [x] integrare completa a doua screen-uri de pe frontend(CRUD complet)
- [x] minim 10 teste de integrare care sa nu foloseasca aceeasi baza de date
- [x] integrare cod cu SonarQube - https://www.sonarsource.com/products/sonarcloud/signup/

Third week
- [x] utilizati AutoMapper pentru a mapa DTO-urile de clasele de domeniu(https://docs.automapper.org/en/stable/Getting-started.html)
- [x] Utilizati FluentValidation pentru a valida business logic-ul aplicatiei pe partea de backend(API)
- [x] toate call-urile catre database trebuie facute async
- [x] eliminati/(explicati cand este cazul) toate Code Smells din SQ
- [x] construiti cel putin doua flow-uri E2E(end to end) care sa aiba in anumite cazuri call-uri catre doua endpoint-uri diferite
- [x] code coverage overall - 70% (trebuie sa fie afisat in SQ)
- [x] eliminati toate problemele semnalate de SQ legate de Security
- [x] finalizati partea de UI/UX pentru 2 screen-uri

Forth week
- [x] functionalitatile noi(trebuie sa ne apropiem de final)
- [x] daca proiectul de FE este facut cu Angular/React - trebuie adaugat in SQ
- [x] code coverage 15% pe FE 🙂
- [x] smart using of FluentValidation (atentie in ce layer se fac validarile)
- [x] 2 controllere trebuie sa foloseasca IMediatr (vezi curs)
- [x] 0 Code Smells
- [x] refactorizati mecanismul de DI (vezi curs)
- [x] versionare pe APIs

Fifth week
- [x] UI/UX done
- [x] Unit testing pe BE => minim 50%
- [x] verificati toate detaliile cerute in requirementurile initiale si asigurati-va ca sunt indeplinite
- [x] voi cere la review anumite portiuni de FE si BE(code quality, best practices)
- [x] pregatiti cea mai dificila parte din aplicatie pentru a fi prezentata
